
version: '3.7'

services:

  # Elasticsearch Docker Images: https://www.docker.elastic.co/
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    # volumes:
    #   - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    healthcheck:
      test: curl -s http://elasticsearch:9200 >/dev/null || exit 1
      interval: 5s
      timeout: 5s
      retries: 10
      # start_period: 40s

  robot: 
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ES_HOST=elasticsearch
    depends_on: 
      elasticsearch:
        condition: service_healthy

# volumes:
#   elasticsearch-data:
#     driver: local